# Generated by Django 4.2 on 2024-03-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unap',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='unap',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user'),
        ),
    ]
