# Generated by Django 4.2 on 2024-03-09 18:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('challenge_title', models.TextField()),
                ('challenge_text', models.TextField()),
                ('challenge_enddate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='user_posts/')),
                ('post_likes', models.IntegerField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=32, validators=[api.models.no_spaces_validator])),
                ('user_pfp', models.ImageField(blank=True, upload_to='user_pfps/')),
                ('user_tokens_owed', models.IntegerField()),
                ('user_wallet_pubkey', models.CharField(max_length=44, validators=[api.models.solanapubkeyvalidator])),
            ],
        ),
        migrations.CreateModel(
            name='userComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='userPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_owed', models.IntegerField()),
                ('user_tokens_updated', models.BooleanField(default=False)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user_id', 'challenge_id')},
            },
        ),
        migrations.CreateModel(
            name='userLikes',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('post_id', 'user_id')},
            },
        ),
    ]
